--DROP TABLE Lin_Fac;
--DROP TABLE Factura;
--DROP TABLE Usuario;
--DROP TABLE Cliente;
--DROP TABLE Articulo;
--DROP TABLE Categoria;
--DROP TABLE IVA;
--DROP SEQUENCE NUM_FACTURA;
--DROP SEQUENCE NUM_USUARIO;
--DROP SEQUENCE NUM_CLIENTE;
--DROP SEQUENCE NUM_IVA;
--DROP SEQUENCE NUM_CATEGORIA;
--DROP SEQUENCE NUM_ARTICULO;

CREATE SEQUENCE NUM_FACTURA;
CREATE SEQUENCE NUM_USUARIO;
CREATE SEQUENCE NUM_CLIENTE;
CREATE SEQUENCE NUM_IVA;
CREATE SEQUENCE NUM_CATEGORIA;
CREATE SEQUENCE NUM_ARTICULO;

CREATE TABLE Usuario (
	id NUMBER PRIMARY KEY ,
	login VARCHAR2(50) UNIQUE NOT NULL,
	mail VARCHAR2(50) UNIQUE NOT NULL,
	role VARCHAR2(50),
	password VARCHAR2(50) NOT NULL);

CREATE TABLE Cliente (
	id NUMBER PRIMARY KEY ,
	nombre VARCHAR2(45) NOT NULL,
	apellidos VARCHAR2(50),
	dni VARCHAR2(10) UNIQUE,
	fecha_nacimiento DATE,
	foto BLOB);
    
CREATE TABLE IVA (
	id NUMBER PRIMARY KEY ,
	porcentaje NUMBER NOT NULL,
	descripcion VARCHAR2(50) NOT NULL
);

CREATE TABLE Categoria (
	id NUMBER PRIMARY KEY,
	descripcion varchar2(45) NOT NULL);
	
CREATE TABLE FACTURA
   (ID NUMBER PRIMARY KEY, 
	FECHAFACTURA DATE DEFAULT (SYSDATE) NOT NULL, 
	BASE NUMBER(10,2) DEFAULT 0 NOT NULL, 
	IVA NUMBER(10,2) DEFAULT 0 NOT NULL, 
	TOTAL NUMBER(10,2) DEFAULT 0 NOT NULL, 
	CLIENTEID NUMBER,
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (CLIENTEID)  REFERENCES JAVA.CLIENTE (ID) );

CREATE TABLE Articulo (
	id NUMBER PRIMARY KEY ,
	descArticulo varchar2(50) NOT NULL,
	existencias NUMBER(10,0) DEFAULT 0 NOT NULL,
	pvp NUMBER(10,2) DEFAULT 0 NOT NULL,
	idIVA NUMBER NOT NULL,
	categoriaId NUMBER NOT NULL,
    CHECK(existencias>=0),
    CHECK(pvp>=0),
	FOREIGN KEY (categoriaId) REFERENCES Categoria (id),
	FOREIGN KEY (idIVA) REFERENCES IVA (id));

CREATE TABLE Lin_Fac (
	facturaId NUMBER NOT NULL,
	linea NUMBER NOT NULL,
	articuloId NUMBER NOT NULL,
	descArticulo varchar2(50) NOT NULL, 
	unidades NUMBER NOT NULL,
	pvp NUMBER(10,2) NOT NULL,
	IVA NUMBER(10,2) NOT NULL,
	importeLinea NUMBER(10,2) NOT NULL,
	PRIMARY KEY (facturaId,linea),
	FOREIGN KEY (facturaId) REFERENCES Factura (id),
	FOREIGN KEY (articuloId) REFERENCES Articulo (id));

CREATE OR REPLACE TRIGGER factura_bir 
BEFORE INSERT ON factura 
FOR EACH ROW

BEGIN
  SELECT NUM_FACTURA.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER IVA_bir 
BEFORE INSERT ON IVA 
FOR EACH ROW

BEGIN
  SELECT NUM_IVA.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER categoria_bir 
BEFORE INSERT ON categoria 
FOR EACH ROW

BEGIN
  SELECT NUM_CATEGORIA.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER cliente_bir 
BEFORE INSERT ON cliente 
FOR EACH ROW

BEGIN
  SELECT NUM_CLIENTE.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
CREATE OR REPLACE TRIGGER usuario_bir 
BEFORE INSERT ON usuario 
FOR EACH ROW

BEGIN
  SELECT NUM_USUARIO.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER articulo_bir 
BEFORE INSERT ON articulo 
FOR EACH ROW

BEGIN
  SELECT NUM_ARTICULO.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/